sudo: false

language: python

python:
  - "2.7_with_system_site_packages"

addons:
  apt:
    sources:
      - mopidy-stable
    packages:
      - mopidy
      - pysiriusxm

env:
  - TOX_ENV=py27
  - TOX_ENV=flake8

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py27' ]; then pip install coveralls; coveralls; fi"


